---
title: "Section 2.3"
author: "Addison"
date: "4/17/2022"
output: html_document
---

# Time series patterns

More careful definitions of "trend" and "seasonal" would be useful.

## Trend

Long period of overall increase or decrease. There may be seasonal ups and downs, but overall there is a general direction. Does not have to be linear.

## Seasonal

Seasonal patterns are where there is a clear effect that lines up with some time period like yearly or weekly. Seasonality is always associated with a fixed time period length.

## Cyclic

Like seasonal, but not associated with a necessarily fixed time period length. Often associated with economic events, or what "business cycles." The duration is typically at least 2 years.

Cyclic and seasonal often confused for one another, but in actuality they are quite different. Figure 2.3 shows different combinations of these components. [[Link to figure]](https://otexts.com/fpp3/tspatterns.html#fig:fourexamples).

1. Top left: No apparent trend. Strong yearly seasonal pattern. Apparent 6-10 year cycle.
2. Top right: Clear downward trend. No clear seasonality. Book mentions more data might reveal the trend is part of a cycle. _I think I can see a potential cycle on the order of 25 years._
3. 



